-- Excel Generate SQL Script
-- for Mysql 
-- =========='2018/9/27 ÐÇÆÚËÄ ÉÏÎç 10:28:38'==========
insert into  FSPA_SEQ_M values ('SEQUENCE_CSPA_FUN_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_CSPA_EXC_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FSPA_EXG_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FSPA_COL_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FSPA_NTB_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_SYS_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_CCY_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_CTY_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_ARE_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_OTP_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_BCH_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FIPA_NUM_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FCMS_IMG_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FCMS_BRO_CNT_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FBTX_APX_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FBTX_APP_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FBTX_NOT_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_BUR_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_BTO_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_ROL_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_RTF_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_BTR_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_BTP_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_SIPA_BTB_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FLOG_OPT_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FLOG_EXP_M',0);
insert into  FSPA_SEQ_M values ('SEQUENCE_FWXM_SAT_M',0);
